CREATE TABLE IF NOT EXISTS Jobs (
    JobId INTEGER PRIMARY KEY AUTOINCREMENT,
    JobName TEXT NOT NULL, 
    Schedule TEXT NOT NULL,
    Host TEXT REFERENCES Hosts(Name) ON DELETE SET NULL,
    Commands TEXT NOT NULL,
    Env TEXT NOT NULL DEFAULT "",
    Hash TEXT NOT NULL UNIQUE,
    Status INTEGER NOT NULL DEFAULT 1,
    Created TEXT NOT NULL DEFAULT (datetime('now')),
    Updated TEXT NOT NULL DEFAULT (datetime('now')),
    LastRun TEXT,
    NextRun TEXT
);

CREATE TABLE IF NOT EXISTS Runs (
    RunId INTEGER PRIMARY KEY AUTOINCREMENT,
    JobId INTEGER REFERENCES Jobs(JobId) ON DELETE SET NULL,
    JobName TEXT NOT NULL,
    Host TEXT NOT NULL,
    StartTime TEXT NOT NULL,
    EndTime TEXT NOT NULL,
    Duration INTEGER NOT NULL,
    ExitCode INTEGER NOT NULL,
    Logs TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Hosts (
    HostId INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL UNIQUE,
    Address TEXT NOT NULL,
    User TEXT NOT NULL,
    Port INTEGER NOT NULL DEFAULT 22,
    KeyPath TEXT NOT NULL DEFAULT "/etc/.ssh/id_ed25519",
    Created TEXT NOT NULL DEFAULT (datetime('now')),
    Updated TEXT NOT NULL DEFAULT (datetime('now'))
);