CREATE TABLE IF NOT EXISTS Jobs (
    JobId INTEGER PRIMARY KEY AUTOINCREMENT,
    JobName TEXT NOT NULL, 
    Schedule TEXT NOT NULL,
    Host TEXT NOT NULL,
    Commands TEXT NOT NULL,
    Env TEXT NOT NULL DEFAULT "",
    JobType TEXT NOT NULL DEFAULT 'Bash',
    JobStatus TEXT NOT NULL DEFAULT 'Active',
    Created TEXT NOT NULL DEFAULT (datetime('now')),
    Updated TEXT NOT NULL DEFAULT (datetime('now')),
    LastRun TEXT,
    NextRun TEXT
);

CREATE TABLE IF NOT EXISTS Runs (
    RunId INTEGER PRIMARY KEY AUTOINCREMENT,
    JobId INTEGER REFERENCES Jobs(Id) ON DELETE SET NULL,
    JobName TEXT NOT NULL,
    Host TEXT NOT NULL,
    StartTime TEXT NOT NULL,
    EndTime TEXT NOT NULL,
    Duration INTEGER NOT NULL,
    ExitCode INTEGER NOT NULL,
    Logs TEXT NOT NULL
);